### ISSUE TITLE
[ASK] Why are you so good with everything

### ISSUE THREAD

**Issue by Namchee** [chez14/ama#1]
Title says all.

What's your secret?

-6C

**Comment by chez14** [comment]
First of all, I'm not that good, you're too kind.

Second, I have no secret(s) for that. Usually, I know how things works by looking it from up above, like, how things works in general. If I wanted to use it, I'll start paying attention to details, but most of times I just use whatever knowledge I have that can make me less digging up that documentation.

Maybe that "secret" ingredient is I know what I'm doing, so whenever that "knowledge" backlashes me, I know how to fix it (hopefully quickly) and most of time can pinpoint to the documentation. Maybe most people didn't see this one =3= in which it happened quite a lot back then.
